#!/bin/bash

### This script is called after the user change environment variables in application setting page.
LOG_FILE="${TRIM_PKGVAR}/info.log"
DATA_PATH="${TRIM_PKGVAR}"
CFG_FILE="${DATA_PATH}/data/config.ini"
SCRIPT_PATH="${TRIM_APPDEST}/server"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

alarm_and_exit() {
    log_msg "$1"
    # 在应用启动、安装、更新等过程中遇到错误时，可以向 TRIM_TEMP_LOGFILE 写入错误信息，然后退出脚本并返回错误码 1
    # 系统会自动将错误日志在前端展示为用户可见的内容（Dialog对话框形式）
    echo "$1" > "${TRIM_TEMP_LOGFILE}"
    exit 1
}

check_port_in_use() {
    local port=$1
    # Linux 用 ss，没有 ss 再用 netstat
    if command -v ss >/dev/null 2>&1; then
        ss -tln | grep -q ":$port "
    elif command -v netstat >/dev/null 2>&1; then
        netstat -tln | grep -q ":$port "
    else
        # 都检测不到就保守一点：当“未占用”继续往下走
        return 1
    fi
}

update_tao_port() {
    local CUR_PORT=$(sed -n 's/^[[:space:]]*port[[:space:]]*=[[:space:]]*\([^#[:space:]]*\).*/\1/p' "${CFG_FILE}" | head -n1)
    if [[ "$CUR_PORT" == "$TAO_PORT" ]]; then
        log_msg "端口相同，跳过修改"
    else
        log_msg "当前端口: ${CUR_PORT}, 目标端口: ${TAO_PORT}"
        if [ "$TAO_PORT" -lt 1024 ]; then
            alarm_and_exit "目标端口 $TAO_PORT 小于 1024，属于系统保留端口，请选择 1024–65535 之间的端口"
        fi
        # 检查目标端口是否被占用
        if check_port_in_use "$TAO_PORT"; then
            alarm_and_exit "端口 $TAO_PORT 已被占用，请改用其他端口"
        fi
        # 修改配置文件中的端口号
        log_msg "修改配置文件中的端口: ${TAO_PORT}"
        sed -i "s|^[[:space:]]*port[[:space:]]*=.*|port=${TAO_PORT}|" "${CFG_FILE}"
    fi
}

update_tao_task_timeout() {
    # 修改配置文件中的任务超时时间
    log_msg "修改配置文件中的任务超时时间: ${TAO_TASK_TIMEOUT}"
    sed -i "s|^[[:space:]]*task_timeout[[:space:]]*=.*|task_timeout=${TAO_TASK_TIMEOUT}|" "${CFG_FILE}"
}

update_tao_expires() {
    # 修改配置文件中的登录有效期
    log_msg "修改配置文件中的登录有效期: ${TAO_EXPIRES}"
    sed -i "s|^[[:space:]]*expires[[:space:]]*=.*|expires=${TAO_EXPIRES}|" "${CFG_FILE}"
}

update_tao_log_level() {
    # 修改配置文件中的日志等级
    log_msg "修改配置文件中的日志等级: ${TAO_LOG_LEVEL}"
    sed -i "s|^[[:space:]]*log_level[[:space:]]*=.*|log_level=${TAO_LOG_LEVEL}|" "${CFG_FILE}"
}

update_tao_console_level() {
    # 修改配置文件中的控制台日志等级
    log_msg "修改配置文件中的控制台日志等级: ${TAO_CONSOLE_LEVEL}"
    sed -i "s|^[[:space:]]*console_level[[:space:]]*=.*|console_level=${TAO_CONSOLE_LEVEL}|" "${CFG_FILE}"
}

update_tao_log_save() {
    # 修改配置文件中的系统日志保留天数
    log_msg "修改配置文件中的系统日志保留天数: ${TAO_LOG_SAVE}"
    sed -i "s|^[[:space:]]*log_save[[:space:]]*=.*|log_save=${TAO_LOG_SAVE}|" "${CFG_FILE}"
}

update_tao_task_save() {
    # 修改配置文件中的任务记录保留天数
    log_msg "修改配置文件中的任务记录保留天数: ${TAO_TASK_SAVE}"
    sed -i "s|^[[:space:]]*task_save[[:space:]]*=.*|task_save=${TAO_TASK_SAVE}|" "${CFG_FILE}"
}