#!/bin/bash

### This script is called after the user change environment variables in application setting page.

source "$(dirname ${BASH_SOURCE[0]})/common"

update_tao_port
update_tao_task_timeout
update_tao_expires
update_tao_log_level
update_tao_console_level
update_tao_log_save
update_tao_task_save

exit 0