#!/bin/bash

### This script is called after the user installs the application.
LOG_FILE="${TRIM_PKGVAR}/info.log"
CFG_FILE="${TRIM_PKGVAR}/AdGuardHome.yaml"
SCRIPT_PATH="${TRIM_APPDEST}/server"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}


log_msg "创建虚拟环境"
bash -c "/usr/bin/python3 -m venv ${SCRIPT_PATH}/.venv" >> ${LOG_FILE} 2>&1

# log_msg "激活虚拟环境"
# bash -c "source ${SCRIPT_PATH}/.venv/bin/activate" >> ${LOG_FILE} 2>&1

log_msg "安装离线依赖"
bash -c "${SCRIPT_PATH}/.venv/bin/pip install --no-index --find-links=${SCRIPT_PATH}/wheels -r ${SCRIPT_PATH}/requirements.txt" >> ${LOG_FILE} 2>&1

log_msg "设置admin账户: ${wizard_admin_username}"
bash -c "cd ${SCRIPT_PATH} && ${SCRIPT_PATH}/.venv/bin/python3 ${SCRIPT_PATH}/update_admin.py ${wizard_admin_username} ${wizard_admin_password}" 2>> ${LOG_FILE} 2>&1
log_msg "已设置admin账号、密码"

exit 0